solarpi/data/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from flask.ext.login import UserMixin

from solarpi.extensions import bcrypt
from solarpi.database import (
    Column,
    db,
    Model,
    SurrogatePK,
)


class Data(SurrogatePK, Model):
    __tablename__ = 'pvdata'

    created_at = Column(db.Text(), nullable=False, default=dt.datetime.utcnow)
    ac_1_u = Column(db.Integer(), nullable=True)
    ac_1_i = Column(db.Float(), nullable=True)
    dc_1_u = Column(db.Integer(), nullable=True)
    dc_1_p = Column(db.Integer(), nullable=True)
    ac_2_u = Column(db.Integer(), nullable=True)
    ac_2_i = Column(db.Float(), nullable=True)
    dc_2_u = Column(db.Integer(), nullable=True)
    dc_2_p = Column(db.Integer(), nullable=True)
    ac_3_u = Column(db.Integer(), nullable=True)
    ac_3_i = Column(db.Float(), nullable=True)
    dc_3_u = Column(db.Integer(), nullable=True)
    dc_3_p = Column(db.Integer(), nullable=True)
    current_power = Column(db.Integer(), nullable=True)
    daily_energy = Column(db.Float(), nullable=True)
    total_energy = Column(db.Integer(), nullable=True)


def __init__(self, username, email, password=None, **kwargs):
    db.Model.__init__(self, **kwargs)

solarpi/electricity/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from solarpi.database import (
    Column,
    db,
    Model,
    SurrogatePK,
)


class Electricity(SurrogatePK, Model):
    __tablename__ = "electricity_data"
    id = Column(db.Integer(), nullable=False, primary_key=True)
    created_at = Column(db.Text(), nullable=False, default=dt.datetime.utcnow)
    meter_180 = Column(db.Float(), nullable=True)
    meter_280 = Column(db.Float(), nullable=True)
    active_power = Column(db.Float(), nullable=True)


def __init__(self):
    db.Model.__init__(self)

solarpi/pvdata/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from solarpi.database import (
    Column,
    db,
    Model,
    SurrogatePK,
)


class PVData(SurrogatePK, Model):
    __tablename__ = "pvdata"

    id = Column(db.Integer(), nullable=False, primary_key=True)
    created_at = Column(db.Text(), nullable=False, default=dt.datetime.utcnow)
    dc_1_u = Column(db.Integer(), nullable=True)
    dc_1_i = Column(db.Float(), nullable=True)
    ac_1_u = Column(db.Integer(), nullable=True)
    ac_1_p = Column(db.Integer(), nullable=True)
    dc_2_u = Column(db.Integer(), nullable=True)
    dc_2_i = Column(db.Float(), nullable=True)
    ac_2_u = Column(db.Integer(), nullable=True)
    ac_2_p = Column(db.Integer(), nullable=True)
    dc_3_u = Column(db.Integer(), nullable=True)
    dc_3_i = Column(db.Float(), nullable=True)
    ac_3_u = Column(db.Integer(), nullable=True)
    ac_3_p = Column(db.Integer(), nullable=True)
    current_power = Column(db.Integer(), nullable=True)
    daily_energy = Column(db.Float(), nullable=True)
    total_energy = Column(db.Integer(), nullable=True)


def __init__(self):
    db.Model.__init__(self)

solarpi/weather/models.py
import datetime as dt

from solarpi.database import (
    Column,
    db,
    Model,
    SurrogatePK,
)


class Weather(SurrogatePK, Model):
    __tablename__ = "weather_data"

    id = Column(db.Integer(), nullable=False, primary_key=True)
    created_at = Column(db.Text(), nullable=False, default=dt.datetime.utcnow)
    temp = Column(db.Float(), nullable=True)
    pressure = Column(db.Integer(), nullable=True)
    temp_min = Column(db.Float(), nullable=True)
    temp_max = Column(db.Float(), nullable=True)
    humidity = Column(db.Integer(), nullable=True)
    wind_speed = Column(db.Float(), nullable=True)
    wind_gust = Column(db.Float(), nullable=True)
    wind_deg = Column(db.Integer(), nullable=True)
    clouds = Column(db.Integer(), nullable=True)
    rain = Column(db.Integer(), nullable=True)
    snow = Column(db.Integer(), nullable=True)
    weather_id = Column(db.Integer(), nullable=True)


def __init__(self):
    db.Model.__init__(self)

solarpi/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""

from flask import Flask, render_template

from solarpi import public, weather, charts, statistics, tables
from solarpi.assets import assets
from solarpi.extensions import cache, db, migrate, debug_toolbar
from solarpi.settings import ProdConfig


def create_app(config_object=ProdConfig):
    """An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    cache.init_app(app, config={"CACHE_TYPE": "simple"})
    db.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    app.register_blueprint(charts.views.blueprint)
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(statistics.views.blueprint)
    app.register_blueprint(tables.views.blueprint)
    app.register_blueprint(weather.views.blueprint)

    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, "code", 500)
        return render_template("{0}.html".format(error_code)), error_code

    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

solarpi/charts/__init__.py
"""The data module."""

from . import views

solarpi/charts/views.py
# -*- coding: utf-8 -*-
import calendar
from datetime import datetime, timedelta

from flask import Blueprint, render_template

from solarpi.charts.helper import get_timestamps, get_daily_pv_chart_data
from solarpi.electricity.helper import get_last_n_days_import, get_last_n_days_export
from solarpi.pvdata.helper import (
    get_sec,
    get_todays_date,
    get_daily_energy_series,
    get_7_day_max_energy_series,
    get_yearly_series,
    get_last_n_days,
    get_current_year_prediction,
)

blueprint = Blueprint("charts", __name__, url_prefix="/charts", static_folder="../static")


@blueprint.route("/daily")
@blueprint.route("/daily/<date>")
def daily(date=None):
    """Renders a page with charts for a given date
    :param date: a date in the format %Y-%m-%d
    :return: page with charts for a given date
    """
    error = None
    current_date = get_todays_date()
    try:
        if date:
            current_date = datetime.strptime(date, "%Y-%m-%d").date()
    except ValueError:
        error = "invalid date, displaying today's data instead"
        current_date = get_todays_date()
    yesterday = current_date - timedelta(days=1)
    tomorrow = current_date + timedelta(days=1)

    # get photovoltaic data for the day
    pv = get_daily_energy_series(current_date)

    daily_chart_data = get_daily_pv_chart_data(pv)

    timestamps_pv = get_timestamps(pv)
    # voltages
    input_voltage_1_chart_data = [list(x) for x in zip(timestamps_pv, [(int(d.dc_1_u or 0)) for d in pv])]
    input_voltage_2_chart_data = [list(x) for x in zip(timestamps_pv, [(int(d.dc_2_u or 0)) for d in pv])]
    output_voltage_1_chart_data = [list(x) for x in zip(timestamps_pv, [(int(d.ac_1_u or 0)) for d in pv])]
    output_voltage_2_chart_data = [list(x) for x in zip(timestamps_pv, [(int(d.ac_2_u or 0)) for d in pv])]
    output_voltage_3_chart_data = [list(x) for x in zip(timestamps_pv, [(int(d.ac_3_u or 0)) for d in pv])]

    # get maxium photovoltaic data for ± 3 days
    pv_max = get_7_day_max_energy_series(current_date)
    current_date_midnight = calendar.timegm(current_date.timetuple())
    timestamps_pv_max = [1000 * (get_sec(d.pvdata_created_at) + current_date_midnight) for d in pv_max]
    daily_chart_max_data = [list(x) for x in zip(timestamps_pv_max, [(int(d.pv_max or 0)) for d in pv_max])]

    # additional data
    daily_energy = 0.0
    if pv:
        daily_energy = pv[-1].daily_energy

    return render_template(
        "charts/daily.html",
        data=daily_chart_data,
        data2=daily_chart_max_data,
        yesterday=yesterday,
        today=current_date,
        tomorrow=tomorrow,
        daily_energy=daily_energy,
        all_data=pv,
        input_voltage_1_chart_data=input_voltage_1_chart_data,
        input_voltage_2_chart_data=input_voltage_2_chart_data,
        output_voltage_1_chart_data=output_voltage_1_chart_data,
        output_voltage_2_chart_data=output_voltage_2_chart_data,
        output_voltage_3_chart_data=output_voltage_3_chart_data,
        error=error,
    )


@blueprint.route("/weekly")
def weekly():
    """Renders a page with charts for the last seven days
    :return: a page with charts for the last seven days
    """
    return get_last_days_chart(number_of_days=7)


@blueprint.route("/monthly")
def monthly():
    """Renders a page with charts for the last 30 days
    :return: a page with charts for the last 30 days
    """
    return get_last_days_chart(number_of_days=30)


def get_last_days_chart(number_of_days=7):
    pv = get_last_n_days(number_of_days)
    timestamps = get_timestamps(pv)
    series = [(float(d.daily_energy or 0)) for d in pv]
    total_energy = sum(series)
    pv_chart_data = [list(x) for x in zip(timestamps, series)]

    electricity_import = [(float(d.daily_import or 0)) for d in get_last_n_days_import(number_of_days)]
    electricity_export = [(float(d.daily_export or 0)) for d in get_last_n_days_export(number_of_days)]
    import_chart_data = [list(x) for x in zip(timestamps, electricity_import)]
    export_chart_data = [list(x) for x in zip(timestamps, electricity_export)]
    return render_template(
        "charts/last_days.html",
        number_of_days=number_of_days,
        pvdata=pv_chart_data,
        importData=import_chart_data,
        exportData=export_chart_data,
        total_energy=total_energy,
    )


@blueprint.route("/yearly")
def yearly():
    """Renders a page with charts for the last years
    :return: a page with charts for the last years
    """
    data = list(get_yearly_series())
    total_energy = sum([x[1] for x in data])
    years = [int(x[0]) for x in data]
    data = [x[1] for x in data]
    yearly_data = len(data) * [5741.82]
    prediction = (len(data) - 1) * ["null"]
    prediction.extend([int(x[0]) for x in list(get_current_year_prediction())])

    return render_template(
        "charts/yearly.html",
        data=data,
        yearlyData=yearly_data,
        total_energy=total_energy,
        prediction=prediction,
        years=years,
    )

solarpi/data/views.py
# -*- coding: utf-8 -*-
import calendar
from datetime import datetime, timedelta

from flask import Blueprint, render_template
from sqlalchemy import extract

from solarpi.data.models import Data

import helper

blueprint = Blueprint("data", __name__, url_prefix='/data',
                      static_folder="../static")


@blueprint.route("/daily")
@blueprint.route("/daily/<date>")
def daily(date=datetime.now().strftime('%Y-%m-%d')):
    try:
        current_date = datetime.strptime(date, "%Y-%m-%d")
    except ValueError, TypeError:
        current_date = datetime.strptime('2014-04-21', "%Y-%m-%d")
    yesterday = current_date - timedelta(days=1)
    tomorrow = current_date + timedelta(days=1)
    data = Data.query.filter(Data.created_at > current_date.strftime('%Y-%m-%d')).filter(
        Data.created_at < tomorrow.strftime('%Y-%m-%d')).filter(Data.current_power > 0)

    daily_energy = data[-1].daily_energy

    categories = [1000 * calendar.timegm(datetime.strptime(d.created_at.split(".")[0], "%Y-%m-%dT%H:%M:%S").timetuple())
                  for d in
                  data]

    series = [(int(d.current_power or 0)) for d in data]
    data = [list(x) for x in zip(categories, series)]

    return render_template("data/daily.html", data=data, yesterday=yesterday, today=current_date, tomorrow=tomorrow,
                           daily_energy=daily_energy)


@blueprint.route("/monthly")
def monthly(date=datetime.now().strftime('%Y-%m-%d')):
    try:
        current_date = datetime.strptime(date, "%Y-%m-%d")
    except ValueError, TypeError:
        current_date = datetime.strptime('2014-04-21', "%Y-%m-%d")
    data = Data.query.filter(extract('year', Data.created_at) == 2014).filter(extract('month', Data.created_at) == 5)

    categories = [1000 * calendar.timegm(datetime.strptime(d.created_at, "%Y-%m-%dT%H:%M:%S").timetuple()) for d in
                  data]
    series = [(float(d.dc_1_p or 0) + float(d.dc_2_p or 0)) for d in data]
    data = [list(x) for x in zip(categories, series)]
    return render_template("data/monthly.html", data=data)

solarpi/electricity/__init__.py
# -*- coding: utf-8 -*-

solarpi/statistics/__init__.py
from . import views

solarpi/statistics/views.py
from flask import Blueprint, render_template

from solarpi.extensions import db, cache

blueprint = Blueprint("statistics", __name__, url_prefix="/statistics", static_folder="../static")


@blueprint.route("/")
@cache.cached(timeout=3600, key_prefix="statistics")
def statistics():
    """Renders a page with statistics for the last 12 months
    :return: a page with statistics for the last 12 months
    """
    data = list(
        db.engine.execute(
            """WITH daily_yield AS (SELECT DATE(created_at)                      AS created_at,
                            MAX(total_energy) - MIN(total_energy) AS daily_yield
                     FROM pvdata
                     GROUP BY DATE(created_at))

                SELECT Strftime('%Y-%m', created_at) AS month,
                       Min(daily_yield)              AS min_yield,
                       Max(daily_yield)              AS max_yield,
                       ROUND(Avg(daily_yield), 2)    AS avg_yield
                FROM daily_yield
                GROUP BY Strftime('%Y-%m', created_at)
                ORDER BY month DESC
                LIMIT 12;
"""
        )
    )
    return render_template("statistics/statistics.html", data=data)

solarpi/tables/__init__.py
from . import views

solarpi/tables/views.py
from datetime import timedelta, datetime

from flask import Blueprint, render_template

from solarpi.extensions import db, cache

blueprint = Blueprint("tables", __name__, url_prefix="/tables", static_folder="../static")


@blueprint.route("/")
@cache.cached(timeout=3600, key_prefix="tables")
def tables():
    """Renders a page with tabulated data for the last 30 days
    :return: a page with tabulated data
    """
    last_30_days = datetime.now() - timedelta(days=30)
    data = db.engine.execute(
        """WITH p AS (SELECT DATE(created_at)   AS created_at,
                  Max(daily_energy)  AS daily_energy,
                  Max(current_power) AS max_output,
                  Max(total_energy)  AS total_energy
           FROM pvdata
           WHERE DATE(created_at) > ?
           GROUP BY DATE(created_at)),

                 e AS (SELECT DATE(created_at)                AS created_at,
                              Max(meter_180) - Min(meter_180) AS daily_import,
                              Max(meter_280) - Min(meter_280) AS daily_export
                       FROM electricity_data
                       WHERE DATE(created_at) > ?
                       GROUP BY DATE(created_at))
            
            SELECT p.*,
                   e.daily_import,
                   e.daily_export
            FROM p
                     JOIN e ON p.created_at = e.created_at
            ORDER BY created_at DESC;
""",
        (last_30_days, last_30_days),
    )
    return render_template("tables/tables.html", data=list(data))

solarpi/weather/__init__.py
"""The weather module."""

from . import views

solarpi/weather/views.py
import calendar
from datetime import datetime, timedelta

from flask import Blueprint, render_template

from solarpi.weather.models import Weather

blueprint = Blueprint("weather", __name__, url_prefix="/weather", static_folder="../static")


@blueprint.route("/daily")
@blueprint.route("/daily/<date>")
def daily(date=datetime.now().strftime("%Y-%m-%d")):
    try:
        current_date = datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        current_date = datetime.strptime("2014-04-21", "%Y-%m-%d")
    yesterday = current_date - timedelta(days=1)
    tomorrow = current_date + timedelta(days=1)
    w = (
        Weather.query.with_entities(Weather.created_at, Weather.temp)
        .filter(Weather.created_at > current_date.strftime("%Y-%m-%d"))
        .filter(Weather.created_at < tomorrow.strftime("%Y-%m-%d"))
        .all()
    )

    timestamps_w = [
        1000 * calendar.timegm(datetime.strptime(d.created_at.split(".")[0], "%Y-%m-%dT%H:%M:%S").timetuple())
        for d in w
    ]
    series_w = [(int(d.temp or 0)) for d in w]
    daily_chart_data = [list(x) for x in zip(timestamps_w, series_w)]

    return render_template(
        "weather/daily.html",
        data=daily_chart_data,
        yesterday=yesterday,
        today=current_date,
        tomorrow=tomorrow,
        all_data=w,
    )

solarpi/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="text-center">
            <h1>401</h1>

            <p>You are not authorized to see this page. Please <a href="{{ url_for('public.login') }}">log in</a>.
            </p>
        </div>
    </div>
{% endblock %}

solarpi/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Christian Stade-Schuldt</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:tafkasorg@yahoo.de">Contact</a></li>
    </ul>
  </small>
</footer>

solarpi/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>
        {% block page_title %} Solar Pi {% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}"/>
    <meta name="keywords" content="solar panel,solar energy,raspberrypi,python,flask"/>
    <meta name="author" content="Christian Stade-Schuldt"/>
    <meta name="google-site-verification" content="EHJ7WpSIIjNMVllNGkTEVgNVnpX_FoxSlheDCm4l-8M"/>

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.9/css/weather-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sb-admin-2.css') }}">

    {% block css %}{% endblock %}

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    {% with form=form %}
        {% include "nav.html" %}
    {% endwith %}

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
</div>
<!-- /#wrapper -->
<script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script type="application/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script type="application/javascript" src="//cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.14/highcharts.js"></script>
<script type="application/javascript" src="//cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.14/highcharts-more.js"></script>
<script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/metisMenu/3.0.4/metisMenu.min.js"></script>
<script type="application/javascript" src="{{ url_for('static', filename='js/sb-admin-2.js') }}"></script>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-708317-16', 'auto');
    ga('send', 'pageview');
</script>
<script src="https://beamanalytics.b-cdn.net/beam.min.js" data-token="b394386b-d8c3-42c8-99de-86dec0537dff" async></script>
{% block scripts %}{% endblock %}
</body>
</html>

solarpi/templates/nav.html
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href={{ url_for('public.home') }}>Solar Pi</a>
    </div>
    <!-- /.navbar-header -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a id="dashboard" class="active" href="{{ url_for('public.home') }}"><i
                            class="fa fa-dashboard fa-fw"></i>
                        Dashboard</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                    <ul id='chart_nav' class="nav nav-second-level">
                        <li>
                            <a id="daily_data" href="{{ url_for('charts.daily') }}">Daily Charts</a>
                        </li>
                        <li>
                            <a id="weekly_data" href="{{ url_for('charts.weekly') }}">Weekly Charts</a>
                        </li>
                        <li>
                            <a id="monthly_data" href="{{ url_for('charts.monthly') }}">Monthly Charts</a>
                        </li>
                        <li>
                            <a id="yearly_data" href="{{ url_for('charts.yearly') }}">Yearly Charts</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a id="tables" href="{{ url_for('tables.tables') }}"><i class="fa fa-table fa-fw"></i> Tables</a>
                </li>
                <li>
                    <a id="statistics" href="{{ url_for('statistics.statistics') }}"><i class="fa fa-signal fa-fw"></i>
                        Statistics</a>
                </li>
                <li>
                    <a id="about" href="{{ url_for('public.about') }}"><i class="fa fa-question fa-fw"></i>
                        About</a>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>